### ISSUE TITLE
chromedriver issue

### ISSUE THREAD

**Issue by alexmat** [jbms/finance-dl#1]
I'm getting the following error when I run the command:

`python3 -m finance_dl.cli --config-module finance_dl_config --config mint`

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.6/site-packages/finance_dl/chromedriver_wrapper.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/site-packages/finance_dl/cli.py", line 91, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/finance_dl/cli.py", line 87, in main
    module.run(**spec)
  File "/usr/lib/python3.6/site-packages/finance_dl/mint.py", line 463, in run
    balances_output_prefix=balances_output_prefix, **kwargs)
  File "/usr/lib/python3.6/site-packages/finance_dl/mint.py", line 435, in fetch_mint_data
    with connect(credentials, kwargs) as mint:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.6/site-packages/finance_dl/mint.py", line 169, in connect
    **scraper_args) as scraper:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.6/site-packages/finance_dl/scrape_lib.py", line 385, in temp_scraper
    headless=headless, **kwargs)
  File "/usr/lib/python3.6/site-packages/finance_dl/mint.py", line 114, in __init__
    super().__init__(use_seleniumrequests=True, **kwargs)
  File "/usr/lib/python3.6/site-packages/finance_dl/scrape_lib.py", line 170, in __init__
    service_args=service_args,
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 88, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver_wrapper.py' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home
```

Any thoughts on how I can fix this?

**Comment by jbms** [comment]
Were you able to resolve this?  Is there something that should be clarified in the documentation?

**Comment by alexmat** [comment]
Sorry I should of been more clear. It was an issue with my install of chromium. I was able to fix it by installing it from another source.

Things are working well otherwise, thanks!
