### ISSUE TITLE
unexpected keyword argument 'required' in add_subparsers

### ISSUE THREAD

**Issue by philipsd6** [jbms/finance-dl#11]
Updated from 1.0.3 to 1.2.0, and am now getting this error:

```
python -m finance_dl.update --config-module finance_dl_config --log-dir logs status
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/...snip.../venvs/beancount/lib/python3.6/site-packages/finance_dl/update.py", line 187, in <module>
    main()
  File "/...snip.../venvs/beancount/lib/python3.6/site-packages/finance_dl/update.py", line 153, in main
    subparsers = ap.add_subparsers(dest='command', required=True)
  File "/usr/lib/python3.6/argparse.py", line 1716, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
TypeError: __init__() got an unexpected keyword argument 'required'
```

**Comment by jbms** [comment]
Thanks for reporting this problem.  It turns out the required parameter is not supported in <Python3.7.  This is now fixed by f5731b8bedc994feee708c76a767c49326c93b07.
