### ISSUE TITLE
Amazon module is failing after reaching 2018 in my order history

### ISSUE THREAD

**Issue by philipsd6** [jbms/finance-dl#16]
My amazon CONFIG:

```python
def CONFIG_amazon():
    return dict(
        module='finance_dl.amazon',
        credentials=amazon.credentials,
        output_directory=os.path.join(data_dir, 'amazon'),
        profile_dir=os.path.join(profile_dir, 'amazon'),
    )
```

After executing the cli:
```sh
python -m finance_dl.cli --config-module finance_dl_config --config amazon --log=INFO
```

The output shows:
```log
 --connect=http://127.0.0.1:57275 --session-id=93c41049e6af86c2d7d455703aed1a63
2019-04-27 15:50:33,070 amazon.py:102 [INFO] Initiating log in                                                                        
2019-04-27 15:50:35,883 amazon.py:109 [INFO] You must be already logged in!
2019-04-27 15:50:38,120 amazon.py:206 [INFO] Retrieving order group: 'last 30 days'                                                   
2019-04-27 15:50:40,159 amazon.py:185 [INFO] Found no more pages
2019-04-27 15:50:40,309 amazon.py:206 [INFO] Retrieving order group: 'past 6 months'                                                  
2019-04-27 15:50:42,365 amazon.py:185 [INFO] Found no more pages  
2019-04-27 15:50:42,536 amazon.py:206 [INFO] Retrieving order group: '2019'                                                           
2019-04-27 15:50:44,433 amazon.py:185 [INFO] Found no more pages
2019-04-27 15:50:44,529 amazon.py:206 [INFO] Retrieving order group: '2018'                                                           
Traceback (most recent call last):                                
  File "/home/philipsd6/devel/finance-dl/finance_dl/scrape_lib.py", line 416, in retry                                                  
    return func()                          
  File "/home/philipsd6/devel/finance-dl/finance_dl/scrape_lib.py", line 436, in fetch                                                  
    scraper.run()                                                                                                                     
  File "/home/philipsd6/devel/finance-dl/finance_dl/amazon.py", line 265, in run                                                        
    self.get_orders(regular=self.regular, digital=self.digital)
  File "/home/philipsd6/devel/finance-dl/finance_dl/amazon.py", line 224, in get_orders
    retrieve_all_order_groups()                                                                                                       
  File "/home/philipsd6/devel/finance-dl/finance_dl/amazon.py", line 209, in retrieve_all_order_groups
    get_invoice_urls()                                                                                                                
  File "/home/philipsd6/devel/finance-dl/finance_dl/amazon.py", line 159, in get_invoice_urls                                           
    invoices, = self.wait_and_return(invoice_finder)
  File "/home/philipsd6/devel/finance-dl/finance_dl/scrape_lib.py", line 252, in wait_and_return                                        
    WebDriverWait(self.driver, timeout).until(predicate, message=message)
  File "/home/philipsd6/.local/venvs/beancount/lib/python3.6/site-packages/selenium/webdriver/support/wait.py", line 80, in until       
    raise TimeoutException(message, screen, stacktrace) 
selenium.common.exceptions.TimeoutException: Message: Waiting to match conditions                                                     
```
This module used to work for me in the past when I first set it up, but now it's failing in 2018.

For "last 30 days", "past 6 months", and "2019" I have < 10 orders and no pagination, but when it gets to "2018" I have > 50 orders, and > 5 pages of orders. This module navigates to the second page of orders for "2018" but then it times out.

The call that is polling until it times out is this:
```
2019-04-27 15:49:40,011 remote_connection.py:388 [DEBUG] POST http://127.0.0.1:37509/session/9a048830f7858ba83482d1a0f641a2bd/elements
{"using": "xpath", "value": "//a[contains(@href, \"summary/print.html\")]", "sessionId": "9a048830f7858ba83482d1a0f641a2bd"}          
2019-04-27 15:49:40,053 connectionpool.py:396 [DEBUG] http://127.0.0.1:37509 "POST /session/9a048830f7858ba83482d1a0f641a2bd/elements H
TTP/1.1" 200 70                                                
```

**Comment by jbms** [comment]
Sounds like maybe a change in the website --- I'll have to take a look.  In general the way I debug these issues is to run in interactive mode.

**Comment by jbms** [comment]
I believe this is fixed now.

**Comment by philipsd6** [comment]
@jbms if you happen to review a closed issue, can you expand a bit somewhere on how you debug these issues in interactive mode? I tried that, and the docs just said call run(), which just does the whole thing, and I didn't have the time/patience to dig into the code to see if I can go step by step to isolate the issue...

**Comment by philipsd6** [comment]
Also, yes, it's working for me now, although it eventually fails due to an Amazon error on downloading an invoice from waaaaaay in the past. I just touched logs/amazon.lastupdate.

**Comment by jbms** [comment]
In interactive mode I usually first call run(), and see where it gets stuck/throws an error.  If it gets stuck, you can press Control+C to interrupt.  You can use the ipython %debug command to enter the debugger, or you can just look at the stack trace to see where it was.  Then I usually manually paste in the relevant snippets of code from the module being executed to see what is being returned.  The ipython shell is set up to attempt to autoreload modified source files, so you can also modify the code to try to fix it and re-run the whole thing or just a particular function to see if it worked.  However, the autoreload does not always work, and generally only works to modify existing methods, not to add new ones.

Regarding it failing on an old invoice, I'm not seeing that on invoices back to 2012 --- if you can figure out a way to detect or handle that it would be great.

Note that the lastupdate file is only used by the status command, but does not affect which invoices are downloaded --- it attempts to download any invoices not already in the output directory.
