### ISSUE TITLE
paypal login breaks when "security challenge" is shown

### ISSUE THREAD

**Issue by notslang** [jbms/finance-dl#20]
Paypal shows a recaptcha after we enter the username / password. However, we navigate away from the security challenge screen before I can click on the recaptcha button.

![1560296704](https://user-images.githubusercontent.com/1049204/59314070-451d7280-8c79-11e9-98ad-737b5a671a62.png)

Here is the log:

```
[0/1] paypal [0s elapsed] starting
[0/1] paypal [2s elapsed] 2019-06-11 18:44:27,880 paypal.py:136 [INFO] Finding username field
[0/1] paypal [2s elapsed] 2019-06-11 18:44:28,016 paypal.py:139 [INFO] Entering username
[0/1] paypal [3s elapsed] 2019-06-11 18:44:28,154 paypal.py:142 [INFO] Finding password field
[0/1] paypal [3s elapsed] 2019-06-11 18:44:29,016 paypal.py:145 [INFO] Entering password
[0/1] paypal [4s elapsed] 2019-06-11 18:44:30,065 paypal.py:149 [INFO] Logged in
[0/1] paypal [4s elapsed] 2019-06-11 18:44:30,065 paypal.py:175 [INFO] Getting transaction list
[0/1] paypal [4s elapsed] 2019-06-11 18:44:30,065 paypal.py:163 [INFO] Getting CSRF token
[0/1] paypal [38s elapsed] Traceback (most recent call last):
[0/1] paypal [38s elapsed]   File "/usr/lib/python3.7/site-packages/finance_dl/scrape_lib.py", line 402, in retry
[0/1] paypal [38s elapsed]     return func()
[0/1] paypal [38s elapsed]   File "/usr/lib/python3.7/site-packages/finance_dl/scrape_lib.py", line 422, in fetch
[0/1] paypal [38s elapsed]     scraper.run()
[0/1] paypal [38s elapsed]   File "/usr/lib/python3.7/site-packages/finance_dl/paypal.py", line 246, in run
[0/1] paypal [38s elapsed]     self.save_transactions()
[0/1] paypal [38s elapsed]   File "/usr/lib/python3.7/site-packages/finance_dl/paypal.py", line 189, in save_transactions
[0/1] paypal [38s elapsed]     transaction_list = self.get_transaction_list()
[0/1] paypal [38s elapsed]   File "/usr/lib/python3.7/site-packages/finance_dl/paypal.py", line 182, in get_transaction_list
[0/1] paypal [38s elapsed]     resp = self.make_json_request(url)
[0/1] paypal [38s elapsed]   File "/usr/lib/python3.7/site-packages/finance_dl/paypal.py", line 156, in make_json_request
[0/1] paypal [38s elapsed]     'x-csrf-token': self.get_csrf_token(),
[0/1] paypal [38s elapsed]   File "/usr/lib/python3.7/site-packages/finance_dl/paypal.py", line 167, in get_csrf_token
[0/1] paypal [38s elapsed]     '//body[@data-token!=""]'))
[0/1] paypal [38s elapsed]   File "/usr/lib/python3.7/site-packages/finance_dl/scrape_lib.py", line 256, in wait_and_locate
[0/1] paypal [38s elapsed]     message='Waiting to locate %r' % (locators, ))
[0/1] paypal [38s elapsed]   File "/usr/lib/python3.7/site-packages/finance_dl/scrape_lib.py", line 238, in wait_and_return
[0/1] paypal [38s elapsed]     WebDriverWait(self.driver, timeout).until(predicate, message=message)
[0/1] paypal [38s elapsed]   File "/usr/lib/python3.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
[0/1] paypal [38s elapsed]     raise TimeoutException(message, screen, stacktrace)
[0/1] paypal [38s elapsed] selenium.common.exceptions.TimeoutException: Message: Waiting to locate (('xpath', '//body[@data-token!=""]'),)
```

**Comment by Zburatorul** [comment]
If this is still relevant, I suggest creating a profile directory for chrome. Point chrome to it and manually log into PayPal. The security challenge should not appear again.

**Comment by Zburatorul** [comment]
Closing due to inactivity and suggested non-code solution.
