### ISSUE TITLE
Mint module does not retry in non-headless state to enter MFA

### ISSUE THREAD

**Issue by johnkferguson** [jbms/finance-dl#23]
Hi,

When using the mint module to download data via mint, it never opens a non-headless browser so I can enter in my MFA information.

In the log below, it says `Retrying login interactively`, but never opens a browser in which I can select and enter my MFA.

```
--connect=http://127.0.0.1:49760 --session-id=e915dc4a973f92fe277f10bb69476134
 --connect=http://127.0.0.1:49774 --session-id=b718b621b3cdd23b9130ad83d8bf5042
2019-11-29 21:25:04,884 mint.py:119 [INFO] Logging into mint
2019-11-29 21:25:10,855 mint.py:123 [INFO] Waiting to enter username and password
2019-11-29 21:25:10,904 mint.py:127 [INFO] Entering username and password
2019-11-29 21:25:11,134 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:12,206 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:13,212 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:14,218 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:15,227 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:16,234 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:17,242 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:18,251 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:19,259 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:20,267 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:21,276 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:22,290 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:23,297 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:24,305 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:25,310 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:26,319 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:27,328 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:28,335 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:29,342 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:30,348 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:31,354 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:32,360 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:33,365 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:34,372 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:35,378 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:36,382 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:37,390 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:38,395 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:39,401 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:40,407 mint.py:135 [INFO] Waiting for MFA
Traceback (most recent call last):
  File "/Users/jkf/accounting/.venv/lib/python3.7/site-packages/finance_dl/mint.py", line 182, in connect
    try_login(scraper)
  File "/Users/jkf/accounting/.venv/lib/python3.7/site-packages/finance_dl/mint.py", line 173, in try_login
    scraper.login()
  File "/Users/jkf/accounting/.venv/lib/python3.7/site-packages/finance_dl/mint.py", line 142, in login
    raise TimeoutError("Login failed to complete within timeout")
TimeoutError: Login failed to complete within timeout
2019-11-29 21:25:41,427 mint.py:195 [INFO] Retrying login interactively
 --connect=http://127.0.0.1:49807 --session-id=c89a622843c182d121d10f26afbc5633
 --connect=http://127.0.0.1:49821 --session-id=9432d53cc738ac098854582993c0c5de
2019-11-29 21:25:43,960 mint.py:119 [INFO] Logging into mint
2019-11-29 21:25:49,641 mint.py:123 [INFO] Waiting to enter username and password
2019-11-29 21:25:49,700 mint.py:127 [INFO] Entering username and password
2019-11-29 21:25:50,004 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:51,014 mint.py:135 [INFO] Waiting for MFA
2019-11-29 21:25:52,018 mint.py:135 [INFO] Waiting for MFA
...
```

**Comment by stonesthatwhisper** [comment]
I was having the same issue. The code forces Mint to be headless, but the login does not work for some reason. If you make sure mintapi installation work with

    python mintapi/api.py --keyring --headless you@example.com  # supply the right path to api.py

It will save a session locally. Then running finance_dl's mint download. It would get further.
