### ISSUE TITLE
PayPal JSON schema changed

### ISSUE THREAD

**Issue by Zburatorul** [jbms/finance-dl#27]
The exception is:
```Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/beancount_import/webserver.py", line 493, in _handle_reconciler_loaded
    loaded_reconciler = loaded_future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/home/user/.local/lib/python3.8/site-packages/beancount_import/thread_helpers.py", line 13, in wrapper
    f.set_result(fn(*args, **kwargs))
  File "/home/user/.local/lib/python3.8/site-packages/beancount_import/reconcile.py", line 396, in __init__
    all_source_results = self._prepare_sources()
  File "/home/user/.local/lib/python3.8/site-packages/beancount_import/reconcile.py", line 515, in _prepare_sources
    source.prepare(self.editor, source_results)
  File "/home/user/.local/lib/python3.8/site-packages/beancount_import/source/paypal.py", line 624, in prepare
    jsonschema.validate(txn, transaction_schema)
  File "/usr/lib/python3/dist-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: 'isCredit' is a required property
```
it occurs on the following object:
```
    {'amount': {'feeAmount': '$0.00',
                'grossAmount': '$19.99',
                'isZeroFee': True,
                'netAmount': '$19.99'},
     'cameFromResCenter': False,
     'cameFromSummary': False,
     'counterparty': {'detailsCounterpartyText': 'Company Inc.',
                      'name': 'Company Inc.'},
     'counterpartyAccountNumber': '123456789',
     'counterpartyBizName': 'Company Name.',
     'flags': {'isBuyer': True,
               'isOrder': True,
               'shouldUpgradeAccount': False},
     'fptiTag': 'orderplaced',
     'isNewActivityUIEnabled': True,
     'links': {'reportDispute': {'linkUrl': '/resolutioncenter/O-0T34207418947273H',
                                 'target': '_blank'},
               'upgradeToBusinessAcct': {'linkUrl': '/US/merchantsignup/router',
                                         'target': ''}},
     'merchantLogoUrl': None,
     'printDetailsLink': {'linkUrl': '/myaccount/transactions/print-orders/O-0T34207418947273H',
                          'target': '_blank'},
     'statusInfo': ['Your payment method will be charged when Company Inc. completes your order.'],
     'transactionId': 'O-0T34207418947273H',
     'transactionType': 'Order Placed',
     'viewContext': 'tdfullpage'}
```

I would appreciate some guidance on how to modify the schema; I'll be happy to submit a PR if I get it fixed.

**Comment by Zburatorul** [comment]
No longer seems to be an issue.
