### ISSUE TITLE
Paypal Selenium TimeoutException

### ISSUE THREAD

**Issue by ikwtif** [jbms/finance-dl#89]
It has been a year+ since I used finance-dl. I tried it on my previous pc where I downloaded finance-dl and imported it as a module locally. I think I messed up my env at some point so I remade it when I wanted to use it again a week ago and nothing 
(only use amazon, paypal) worked. Now I'm at a point that I can actually login again on paypal but now I'm getting this error.  

Anyone can supply a requirements file? I had a lot of issues getting up to this point because of newer version packages that don't work. 
Now I got up to a point I have a persistent google profile, which loads paypal but then just runs into this error. This is when the paypal page is on the activities page. 

I also noticed this is an issue with the CSFR token? Because I found this in the paypal file, might be an issue with paypal already being on activities page? 
```
    def get_csrf_token(self):
        if self.csrf_token is not None: return self.csrf_token
        logging.info('Getting CSRF token')
        self.driver.get('https://www.paypal.com/myaccount/transactions/')
        # Get CSRF token
        body_element, = self.wait_and_locate((By.XPATH,
                                              '//body[@data-token!=""]'))
        self.csrf_token = body_element.get_attribute('data-token')
        return self.csrf_token
```

```
Traceback (most recent call last):
  File "C:\Users\Dieter\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Dieter\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "d:\finance\import beancount\finance-dl\finance_dl\cli.py", line 91, in <module>
    main()
  File "d:\finance\import beancount\finance-dl\finance_dl\cli.py", line 87, in main
    module.run(**spec)
  File "d:\finance\import beancount\finance-dl\finance_dl\paypal.py", line 270, in run
    scrape_lib.run_with_scraper(Scraper, **kwargs)
  File "d:\finance\import beancount\finance-dl\finance_dl\scrape_lib.py", line 424, in run_with_scraper
    retry(fetch)
  File "d:\finance\import beancount\finance-dl\finance_dl\scrape_lib.py", line 402, in retry
    return func()
  File "d:\finance\import beancount\finance-dl\finance_dl\scrape_lib.py", line 422, in fetch
    scraper.run()
  File "d:\finance\import beancount\finance-dl\finance_dl\paypal.py", line 266, in run
    self.save_transactions()
  File "d:\finance\import beancount\finance-dl\finance_dl\paypal.py", line 207, in save_transactions
    transaction_list = self.get_transaction_list()
  File "d:\finance\import beancount\finance-dl\finance_dl\paypal.py", line 196, in get_transaction_list
    resp = self.make_json_request(url)
  File "d:\finance\import beancount\finance-dl\finance_dl\paypal.py", line 169, in make_json_request
    'x-csrf-token': self.get_csrf_token(),
  File "d:\finance\import beancount\finance-dl\finance_dl\paypal.py", line 180, in get_csrf_token
    body_element, = self.wait_and_locate((By.XPATH,
  File "d:\finance\import beancount\finance-dl\finance_dl\scrape_lib.py", line 254, in wait_and_locate
    return self.wait_and_return(
  File "d:\finance\import beancount\finance-dl\finance_dl\scrape_lib.py", line 238, in wait_and_return
    WebDriverWait(self.driver, timeout).until(predicate, message=message)
  File "D:\Finance\Import Beancount\env\lib\site-packages\selenium\webdriver\support\wait.py", line 87, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Waiting to locate (('xpath', '//body[@data-token!=""]'),)
Stacktrace:
        GetHandleVerifier [0x00007FF61DA08EF2+54786]
        (No symbol) [0x00007FF61D975612]
        (No symbol) [0x00007FF61D82A64B]
        (No symbol) [0x00007FF61D86B79C]
        (No symbol) [0x00007FF61D86B91C]
        (No symbol) [0x00007FF61D8A6D87]
        (No symbol) [0x00007FF61D88BEAF]
        (No symbol) [0x00007FF61D8A4D02]
        (No symbol) [0x00007FF61D88BC43]
        (No symbol) [0x00007FF61D860941]
        (No symbol) [0x00007FF61D861B84]
        GetHandleVerifier [0x00007FF61DD57F52+3524194]
        GetHandleVerifier [0x00007FF61DDAD800+3874576]
        GetHandleVerifier [0x00007FF61DDA5D7F+3843215]
        GetHandleVerifier [0x00007FF61DAA5086+694166]
        (No symbol) [0x00007FF61D980A88]
        (No symbol) [0x00007FF61D97CA94]
        (No symbol) [0x00007FF61D97CBC2]
        (No symbol) [0x00007FF61D96CC83]
        BaseThreadInitThunk [0x00007FFC4336257D+29]
        RtlUserThreadStart [0x00007FFC4428AA78+40]
```

**Comment by ikwtif** [comment]
Just noticed I'm still using the old version and the get_csrf_token function was updated so I'll try with the last version
