### ISSUE TITLE
Amazon(.co.uk) not seeing orders

### ISSUE THREAD

**Issue by ikwtif** [jbms/finance-dl#91]
Can't really provide much more info since there isn't any error

```
DevTools listening on ws://127.0.0.1:50082/devtools/browser/f72cd410-a08b-41e8-ab1a-cc6b26aad299
 --connect=http://localhost:50079 --session-id=7d8f0a6373be86bc7ee5a26c1d39f98d
2023-10-29 21:55:41,054 amazon.py:277 [INFO] Initiating log in
2023-10-29 21:55:41,608 amazon.py:288 [INFO] Looking for sign-in link
2023-10-29 21:55:41,943 amazon.py:294 [INFO] Looking for username link
2023-10-29 21:55:42,388 amazon.py:304 [INFO] Looking for password link
2023-10-29 21:55:42,435 amazon.py:310 [INFO] Looking for "remember me" checkbox
2023-10-29 21:55:43,689 amazon.py:319 [INFO] Logged in
2023-10-29 21:55:44,225 amazon.py:464 [INFO] Retrieving order group: 'last 30 days'
2023-10-29 21:55:44,611 amazon.py:436 [INFO] Found no more pages
2023-10-29 21:55:44,639 amazon.py:464 [INFO] Retrieving order group: 'past three months'
2023-10-29 21:55:45,041 amazon.py:436 [INFO] Found no more pages
2023-10-29 21:55:45,068 amazon.py:464 [INFO] Retrieving order group: '2023'
2023-10-29 21:55:45,878 amazon.py:436 [INFO] Found no more pages
2023-10-29 21:55:45,910 amazon.py:464 [INFO] Retrieving order group: '2022'
2023-10-29 21:55:46,303 amazon.py:436 [INFO] Found no more pages
2023-10-29 21:55:46,331 amazon.py:464 [INFO] Retrieving order group: '2021'
2023-10-29 21:55:47,726 amazon.py:436 [INFO] Found no more pages
2023-10-29 21:55:47,753 amazon.py:464 [INFO] Retrieving order group: '2020'
2023-10-29 21:55:48,153 amazon.py:436 [INFO] Found no more pages
2023-10-29 21:55:48,178 amazon.py:464 [INFO] Retrieving order group: '2019'
2023-10-29 21:55:48,568 amazon.py:436 [INFO] Found no more pages
2023-10-29 21:55:48,599 amazon.py:464 [INFO] Retrieving order group: '2018'
2023-10-29 21:55:49,003 amazon.py:436 [INFO] Found no more pages
2023-10-29 21:55:49,033 amazon.py:464 [INFO] Retrieving order group: '2017'
2023-10-29 21:55:49,438 amazon.py:436 [INFO] Found no more pages
2023-10-29 21:55:49,464 amazon.py:464 [INFO] Retrieving order group: '2016'
2023-10-29 21:55:49,875 amazon.py:436 [INFO] Found no more pages
2023-10-29 21:55:49,902 amazon.py:464 [INFO] Retrieving order group: '2015'
2023-10-29 21:55:50,319 amazon.py:436 [INFO] Found no more pages
```

**Comment by ikwtif** [comment]
has to change` View order` to `View order details `

`invoice_link=["View order details", "View invoice"],`

https://github.com/jbms/finance-dl/blob/4b8e28a29b8f0faf5ab3457b5cded2079e73f3fd/finance_dl/amazon.py#L175C1-L175C1

still getting errors while downloading an order, I guess a couple things changed on the site

```
2023-10-29 22:12:56,371 amazon.py:495 [INFO] Downloading invoice for order '026-0963528-2937141'
Traceback (most recent call last):
  File "D:\Finance\finance-dl-master\finance_dl\scrape_lib.py", line 403, in retry
    return func()
  File "D:\Finance\finance-dl-master\finance_dl\scrape_lib.py", line 423, in fetch
    scraper.run()
  File "D:\Finance\finance-dl-master\finance_dl\amazon.py", line 585, in run
    self.get_orders(
  File "D:\Finance\finance-dl-master\finance_dl\amazon.py", line 491, in get_orders
    self.retrieve_invoices(invoice_hrefs)
  File "D:\Finance\finance-dl-master\finance_dl\amazon.py", line 562, in retrieve_invoices
    order_date = get_date(page_source, order_id)
  File "D:\Finance\finance-dl-master\finance_dl\amazon.py", line 556, in get_date
    m = re.fullmatch(regex, node.text.strip())
AttributeError: 'NoneType' object has no attribute 'text'
```
